apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unit-tests
spec:
  destination:
    name: ""
    namespace: unit
    server: "https://kubernetes.default.svc"
  source:
    path: functional/01-unit/02-manifests/03-tests
    repoURL: "https://github.com/isaldarriaga/service-mesh-stress.git"
    targetRevision: HEAD
    directory:
      recurse: false
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
