apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unit-tests
spec:
  destination:
    name: "in-cluster"
    namespace: unit
    server: "https://kubernetes.default.svc"
  source:
    path: functional/01-unit/02-manifests/03-tests
    repoURL: "https://github.com/isaldarriaga/polyglot-infra-code.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
